name: Custom Windows VNC

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Getting Updates and Installing Tailscale, Git.
        run: |
          sudo apt update -y
          sudo apt install git wget -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Run
        run: |
             sudo apt update -y
             sudo apt install yaru-theme-gtk yaru-theme-icon -y
             sudo apt install websockify novnc gnome-shell gnome-terminal gnome-tweaks gnome-shell-extensions gnome-shell-extension-ubuntu-dock nautilus nano gedit dbus-x11 tigervnc-standalone-server -y
             mkdir ~/.vnc
             wget https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/main/pass.py
             pip install pycryptodome --quiet
             python pass.py
             chmod 600 /tmp/vnc_passwd
             chmod +x /tmp/vnc_passwd
             cp /tmp/vnc_passwd ~/.vnc/passwd
             rm /tmp/vnc_passwd
             wget -O ~/.vnc/xstartup https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/main/xstartup
             wget -O loop.sh https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/main/loop.sh
             sh loop.sh
