name: Ubuntu XFCE VNC (without vbox)

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Getting Updates and Installing Tailscale, Git.
        run: |
          sudo apt update -y
          sudo apt install git wget -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --ssh
      - name: Run
        run: |
             sudo apt update -y
             sudo apt install xfce4 xfce4-goodies -y
             sudo apt install websockify novnc tigervnc-standalone-server -y
             mkdir ~/.vnc
             wget -O ~/.vnc/xstartup https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/main/startup
             chmod +x /home/runner/.vnc/xstartup
             chmod 666 /home/runner/.vnc/xstartup
             wget -O loop.sh https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/main/loop.sh
             sh loop.sh
